import { z } from "zod";

const nullableString = z.string().nullable();
const nullableNumber = z.number().finite().nullable();

const JamaicaTariffRatesSchema = z.object({
  importDuty: nullableString,
  additionalStampDuty: nullableString,
  gct: nullableString,
  excise: nullableString,
  scta: nullableString,
  scts: nullableString,
  sctf: nullableString,
  standardComplianceFee: nullableString,
  environmentalLevy: nullableString,
  developmentCess: nullableString,
  raw: z.array(z.string()),
});

export const EditableLineItemSchema = z.object({
  lineNumber: z.number().int().positive(),
  articleNumber: nullableString,
  commercialDescription: z.string(),
  rawHsCode: nullableString,
  suggestedHsCode: nullableString,
  hsCodeConfidence: z.number().min(0).max(1).nullable(),
  quantity: nullableNumber,
  unitOfMeasure: nullableString,
  packageType: nullableString,
  packageCount: nullableNumber,
  statisticalQuantity: nullableNumber,
  countryOfOrigin: nullableString,
  grossWeightKg: nullableNumber,
  netWeightKg: nullableNumber,
  unitPrice: nullableNumber,
  lineTotal: nullableNumber,
  extractionConfidence: z.number().min(0).max(1),
  warnings: z.array(z.string()),
  normalizedCommodityCode: z.string(),
  precision: z.string(),
  precision1: nullableString,
  precision2: nullableString,
  precision3: nullableString,
  precision4: nullableString,
  confirmedHsCode: nullableString,
  hsConfirmed: z.boolean(),
  includeInXml: z.boolean(),
  hsSource: z.enum(["invoice", "ai-suggestion", "manual", "saved-mapping", "jca-tariff"]),
  officialJamaicaTariffCode: nullableString.optional(),
  officialTariffDescription: nullableString.optional(),
  officialTariffUnits: z.array(z.string()).optional(),
  officialTariffRates: JamaicaTariffRatesSchema.nullable().optional(),
  officialTariffEffectiveDate: nullableString.optional(),
  officialTariffSourceUrl: nullableString.optional(),
  officialTariffSource: z.enum(["jca-pdf-2026", "jamaica-trade-portal-public", "jamaica-trade-portal-api"]).nullable().optional(),
  tariffVerified: z.boolean().optional(),
});

export const DeclarationDraftSchema = z.object({
  source: z.enum(["ai", "manual", "demo"]),
  warnings: z.array(z.string()),
  commercialReference: z.object({ year: z.string(), number: z.string() }),
  declaration: z.object({
    declarantName: z.string(),
    declarantCode: nullableString,
    declarantRepresentative: nullableString,
    regimeType: nullableString,
    declarationType: nullableString,
    generalProcedureCode: nullableString,
    extendedProcedure: nullableString,
    nationalProcedure: nullableString,
    customsOfficeCode: nullableString,
    customsOfficeName: nullableString,
    borderOfficeCode: nullableString,
    borderOfficeName: nullableString,
    locationOfGoods: nullableString,
    exportCountry: nullableString,
    exportCountryName: nullableString,
    destinationCountry: nullableString,
    destinationCountryName: nullableString,
    defaultCountryOfOrigin: nullableString,
    currency: nullableString,
    exchangeRate: nullableString,
    totalPackages: nullableNumber,
    packageCode: nullableString,
    packageName: nullableString,
    marksAndNumbers: nullableString,
    containerNumber: nullableString,
    containerFlag: z.boolean(),
    transportMode: nullableString,
    placeOfLoadingCode: nullableString,
    placeOfLoadingName: nullableString,
    deliveryTermCode: nullableString,
    deliveryTermRaw: nullableString,
    deferredPaymentRef: nullableString,
    modeOfPayment: nullableString,
  }),
  seller: z.object({
    name: nullableString,
    address: nullableString,
    countryCode: nullableString,
    exporterCode: nullableString,
  }),
  consignee: z.object({
    name: z.string(),
    address: nullableString,
    countryCode: nullableString,
    trn: nullableString,
  }),
  responsibleParty: z.object({ name: nullableString, code: nullableString }),
  shipment: z.object({
    vessel: nullableString,
    carrier: nullableString,
    containerNumber: nullableString,
    sealNumber: nullableString,
    bookingNumber: nullableString,
    billOfLading: nullableString,
    manifestReference: nullableString,
    transportMode: nullableString,
    borderOfficeCode: nullableString,
    borderOfficeName: nullableString,
    placeOfLoadingCode: nullableString,
    placeOfLoadingName: nullableString,
    locationOfGoods: nullableString,
    deliveryTermRaw: nullableString,
    deliveryTermCode: nullableString,
    grossWeightKg: nullableNumber,
  }),
  invoice: z.object({
    number: nullableString,
    date: nullableString,
    currency: nullableString,
    exchangeRate: nullableString,
    merchandiseValue: nullableString,
    freightValue: nullableString,
    insuranceValue: nullableString,
    totalValue: nullableString,
  }),
  items: z.array(EditableLineItemSchema),
});
