import type { InvoiceExtractionResult } from "./types";

/** PriceSmart commercial invoice fixture. Values are labeled demo data in the UI. */
export const PRICEMART_DEMO_EXTRACTION: InvoiceExtractionResult = {
  documentType: "commercial_invoice",
  seller: {
    name: "PriceSmart, Inc.",
    address: "9797 Aero Drive, Suite 100, San Diego, CA 92123",
    countryCode: "US",
  },
  consignee: {
    name: null,
    address: null,
    countryCode: "JM",
    trn: null,
  },
  shipment: {
    containerNumber: "SMLU7871623",
    bookingNumber: "9135632",
    carrier: "Seaboard Marine Ltd",
    vessel: "Seaboard Globe V83",
    sealNumber: "48012",
    sailDate: "2026-07-17",
    etaDate: "2026-07-19",
    billOfLading: null,
    manifestReference: null,
    incotermRaw: "C&I (Cost & Insurance)",
    grossWeightKg: 7802,
  },
  invoice: {
    invoiceNumber: null,
    invoiceDate: null,
    currency: "USD",
    merchandiseValue: 80755.23,
    insuranceValue: 24.23,
    freightValue: null,
    totalValue: 80779.46,
  },
  packages: [
    { packageType: "PL", quantity: 19 },
    { packageType: "CS", quantity: 6 },
  ],
  items: [
    {
      lineNumber: 1,
      articleNumber: "712294",
      commercialDescription: "Custom Safe B-Rate 60x40x25",
      rawHsCode: "8303.00.00.0",
      suggestedHsCode: null,
      hsCodeConfidence: null,
      quantity: 1,
      unitOfMeasure: "NMB",
      packageType: "PL",
      packageCount: 1,
      statisticalQuantity: 1,
      countryOfOrigin: "US",
      grossWeightKg: 453.5147,
      netWeightKg: null,
      unitPrice: 6334.38,
      lineTotal: 6334.38,
      extractionConfidence: 0.95,
      warnings: [],
    },
    {
      lineNumber: 2,
      articleNumber: "170770",
      commercialDescription: "Hand Pallet Truck - Crown",
      rawHsCode: "8425.49.00.0",
      suggestedHsCode: null,
      hsCodeConfidence: null,
      quantity: 10,
      unitOfMeasure: "NMB",
      packageType: "PL",
      packageCount: 10,
      statisticalQuantity: 10,
      countryOfOrigin: "CN",
      grossWeightKg: 770.9751,
      netWeightKg: null,
      unitPrice: 617.06,
      lineTotal: 6170.6,
      extractionConfidence: 0.95,
      warnings: [],
    },
    {
      lineNumber: 3,
      articleNumber: "783178",
      commercialDescription: "Rotary Pizza Sauce Dispenser",
      rawHsCode: "8438.80.00.0",
      suggestedHsCode: null,
      hsCodeConfidence: null,
      quantity: 1,
      unitOfMeasure: "NMB",
      packageType: "PL",
      packageCount: 1,
      statisticalQuantity: 1,
      countryOfOrigin: "US",
      grossWeightKg: 68.0272,
      netWeightKg: null,
      unitPrice: 10221.11,
      lineTotal: 10221.11,
      extractionConfidence: 0.95,
      warnings: [],
    },
    {
      lineNumber: 4,
      articleNumber: "771321",
      commercialDescription: "Register Stand; KCu3500; V.3",
      rawHsCode: "9403.60.90.0",
      suggestedHsCode: null,
      hsCodeConfidence: null,
      quantity: 6,
      unitOfMeasure: "NMB",
      packageType: "CS",
      packageCount: 6,
      statisticalQuantity: 6,
      countryOfOrigin: "US",
      grossWeightKg: 1768.7075,
      netWeightKg: null,
      unitPrice: 4699.0083,
      lineTotal: 28194.05,
      extractionConfidence: 0.95,
      warnings: [],
    },
    {
      lineNumber: 5,
      articleNumber: "771320",
      commercialDescription: "Register Stand; KCu3500; V.3",
      rawHsCode: "9403.60.90.0",
      suggestedHsCode: null,
      hsCodeConfidence: null,
      quantity: 6,
      unitOfMeasure: "NMB",
      packageType: "PL",
      packageCount: 6,
      statisticalQuantity: 6,
      countryOfOrigin: "US",
      grossWeightKg: 816.3265,
      netWeightKg: null,
      unitPrice: 4699.0083,
      lineTotal: 28194.05,
      extractionConfidence: 0.95,
      warnings: [],
    },
    {
      lineNumber: 6,
      articleNumber: "771322",
      commercialDescription: "Scanner Center Module",
      rawHsCode: "9403.60.90.0",
      suggestedHsCode: null,
      hsCodeConfidence: null,
      quantity: 1,
      unitOfMeasure: "NMB",
      packageType: "PL",
      packageCount: 1,
      statisticalQuantity: 1,
      countryOfOrigin: "US",
      grossWeightKg: 45.3515,
      netWeightKg: null,
      unitPrice: 1665.27,
      lineTotal: 1665.27,
      extractionConfidence: 0.95,
      warnings: [],
    },
  ],
  warnings: [
    "Consignee information is not clearly available on the invoice.",
    "Declarant information is not available.",
    "Manifest reference is not available.",
    "BL/AWB is not clearly available.",
    "The raw 'C&I' term should not be silently converted to CIF.",
    "Shipment gross weight (7,802 kg) differs significantly from the sum of item weights (~3,923 kg).",
  ],
};
